name: if-function
on:
 push:
   branches:
     - main
     - feature
     - develop
jobs:
  code-quality:
   if: startsWith(github.ref_name,'features') && github.event_name == 'push'
   runs-on: ubuntu-latest
   steps:
     - name: performcode quality
     - run: echo "deploying code on evn"
  deploy-to-devloper:
    if: github.ref_name=='develop' && github.event_name== 'push'
    runs-on: ubuntu-latest
    steps:
      - name: perform at devlop level
        run: echo "deploying in to devlop level"
  deploy to production:
    if: github.event_name== 'main' && github.event_name== 'push'
    runs-on: ubuntu-latest
    steps:
      - name: dploy at production
        run: echo "deploying into productionlevel"    
     
