name: if-test-02
on: 
  push:
    branches:
      - main
      - test
jobs:
  ifcase-2:
    runs-on: ubuntu-latest
    steps:
      - name: if case
        if: github.actor =='vasanth' || github.actor == 'vasanth-kvn'
        run: echo "run if case work"
      - name: manual
        run: echo "my manually worked"
        
